### ISSUE TITLE
2 tests fail on FreeBSD when run with pytest from the ports tree

### ISSUE THREAD

**Issue by yurivict** [pypa/distlib#205] opened 2023-07-18 06:16 UTC
**Describe the bug**
```
========================================================================================== FAILURES ===========================================================================================
_______________________________________________________________________________ LocatorTestCase.test_dist_reqts _______________________________________________________________________________

self = <test_locators.LocatorTestCase testMethod=test_dist_reqts>

    @unittest.skipIf('SKIP_ONLINE' in os.environ, 'Skipping online test')
    @unittest.skipUnless(ssl, 'SSL required for this test.')
    def test_dist_reqts(self):
        r = 'config <=0.3.9'
        dist = default_locator.locate(r)
        self.assertIsNotNone(dist)
>       self.assertIsNone(dist.extras)
E       AssertionError: ['doc', 'test'] is not None

tests/test_locators.py:423: AssertionError
______________________________________________________________________________ UtilTestCase.test_sequencer_basic ______________________________________________________________________________

self = <test_util.UtilTestCase testMethod=test_sequencer_basic>

    def test_sequencer_basic(self):
        seq = Sequencer()
    
        steps = (
            ('check', 'sdist'),
            ('check', 'register'),
            ('check', 'sdist'),
            ('check', 'register'),
            ('register', 'upload_sdist'),
            ('sdist', 'upload_sdist'),
            ('check', 'build_clibs'),
            ('build_clibs', 'build_ext'),
            ('build_ext', 'build_py'),
            ('build_py', 'build_scripts'),
            ('build_scripts', 'build'),
            ('build', 'test'),
            ('register', 'upload_bdist'),
            ('build', 'upload_bdist'),
            ('build', 'install_headers'),
            ('install_headers', 'install_lib'),
            ('install_lib', 'install_scripts'),
            ('install_scripts', 'install_data'),
            ('install_data', 'install_distinfo'),
            ('install_distinfo', 'install')
        )
    
        for pred, succ in steps:
            seq.add(pred, succ)
    
        # Note: these tests are sensitive to dictionary ordering
        # but work under Python 2.6, 2.7, 3.2, 3.3, 3.4 and PyPy 2.5
        cases = (
            ('check', ['check']),
            ('register', ['check', 'register']),
            ('sdist', ['check', 'sdist']),
            ('build_clibs', ['check', 'build_clibs']),
            ('build_ext', ['check', 'build_clibs', 'build_ext']),
            ('build_py', ['check', 'build_clibs', 'build_ext', 'build_py']),
            ('build_scripts', ['check', 'build_clibs', 'build_ext', 'build_py',
                               'build_scripts']),
            ('build', ['check', 'build_clibs', 'build_ext', 'build_py',
                       'build_scripts', 'build']),
            ('test', ['check', 'build_clibs', 'build_ext', 'build_py',
                      'build_scripts', 'build', 'test']),
            ('install_headers', ['check', 'build_clibs', 'build_ext',
                                 'build_py', 'build_scripts', 'build',
                                 'install_headers']),
            ('install_lib', ['check', 'build_clibs', 'build_ext', 'build_py',
                             'build_scripts', 'build', 'install_headers',
                             'install_lib']),
            ('install_scripts', ['check', 'build_clibs', 'build_ext',
                                 'build_py', 'build_scripts', 'build',
                                 'install_headers', 'install_lib',
                                 'install_scripts']),
            ('install_data', ['check', 'build_clibs', 'build_ext', 'build_py',
                              'build_scripts', 'build', 'install_headers',
                              'install_lib', 'install_scripts',
                              'install_data']),
            ('install_distinfo', ['check', 'build_clibs', 'build_ext',
                                  'build_py', 'build_scripts', 'build',
                                  'install_headers', 'install_lib',
                                  'install_scripts', 'install_data',
                                  'install_distinfo']),
            ('install', ['check', 'build_clibs', 'build_ext', 'build_py',
                         'build_scripts', 'build', 'install_headers',
                         'install_lib', 'install_scripts', 'install_data',
                         'install_distinfo', 'install']),
            ('upload_sdist', (['check', 'register', 'sdist', 'upload_sdist'],
                              ['check', 'sdist', 'register', 'upload_sdist'])),
            ('upload_bdist', (['check', 'build_clibs', 'build_ext', 'build_py',
                               'build_scripts', 'build', 'register',
                               'upload_bdist'],
                              ['check', 'build_clibs', 'build_ext', 'build_py',
                               'build_scripts', 'register', 'build',
                               'upload_bdist'])),
        )
    
        for final, expected in cases:
            actual = list(seq.get_steps(final))
            if isinstance(expected, tuple):
                self.assertIn(actual, expected)
            else:
                self.assertEqual(actual, expected)
    
        dot = seq.dot
        expected = '''
        digraph G {
          check -> build_clibs;
          install_lib -> install_scripts;
          register -> upload_bdist;
          build -> upload_bdist;
          build_ext -> build_py;
          install_scripts -> install_data;
          check -> sdist;
          check -> register;
          build -> install_headers;
          install_data -> install_distinfo;
          sdist -> upload_sdist;
          register -> upload_sdist;
          install_distinfo -> install;
          build -> test;
          install_headers -> install_lib;
          build_py -> build_scripts;
          build_clibs -> build_ext;
          build_scripts -> build;
        }
        '''
        expected = textwrap.dedent(expected).strip().splitlines()
        actual = dot.splitlines()
        self.assertEqual(expected[0], actual[0])
        self.assertEqual(expected[-1], actual[-1])
        self.assertEqual(set(expected[1:-1]), set(actual[1:-1]))
        actual = seq.strong_connections
        expected = (
            [
                ('test',), ('upload_bdist',), ('install',),
                ('install_distinfo',), ('install_data',), ('install_scripts',),
                ('install_lib',), ('install_headers',), ('build',),
                ('build_scripts',), ('build_py',), ('build_ext',),
                ('build_clibs',), ('upload_sdist',), ('sdist',), ('register',),
                ('check',)
            ],
            [
                ('install',), ('install_distinfo',), ('install_data',),
                ('install_scripts',), ('install_lib',), ('install_headers',),
                ('test',), ('upload_bdist',), ('build',), ('build_scripts',),
                ('build_py',), ('build_ext',), ('build_clibs',),
                ('upload_sdist',), ('sdist',), ('register',), ('check',)
            ],
            [
                ('upload_sdist',), ('sdist',), ('install',),
                ('install_distinfo',), ('install_data',), ('upload_bdist',),
                ('register',), ('install_scripts',), ('install_lib',),
                ('install_headers',), ('test',), ('build',),
                ('build_scripts',), ('build_py',), ('build_ext',),
                ('build_clibs',), ('check',)
            ],
            # Next case added for PyPy
            [
                ('upload_sdist',), ('sdist',), ('upload_bdist',), ('register',),
                ('test',), ('install',), ('install_distinfo',),
                ('install_data',), ('install_scripts',), ('install_lib',),
                ('install_headers',), ('build',), ('build_scripts',),
                ('build_py',), ('build_ext',), ('build_clibs',), ('check',)
            ],
            # Next case added for Python 3.6
            [
                ('upload_sdist',), ('sdist',), ('upload_bdist',), ('register',),
                ('install',), ('install_distinfo',), ('install_data',),
                ('install_scripts',), ('install_lib',), ('install_headers',),
                ('test',), ('build',), ('build_scripts',), ('build_py',),
                ('build_ext',), ('build_clibs',), ('check',)
            ],
            # Next case added for Python 3.11
            [
                ('upload_sdist',), ('sdist',), ('install',), ('install_distinfo',),
                ('install_data',), ('install_scripts',), ('install_lib',),
                ('install_headers',), ('test',), ('upload_bdist',), ('build',),
                ('build_scripts',), ('build_py',), ('build_ext',), ('build_clibs',),
                ('register',), ('check',)
            ]
        )
>       self.assertIn(actual, expected)
E       AssertionError: [('test',), ('install',), ('install_distinfo',), ('install_data',), ('install_scripts',), ('install_lib',), ('install_headers',), ('upload_bdist',), ('build',), ('build_scripts',), ('build_py',), ('build_ext',), ('build_clibs',), ('upload_sdist',), ('sdist',), ('register',), ('check',)] not found in ([('test',), ('upload_bdist',), ('install',), ('install_distinfo',), ('install_data',), ('install_scripts',), ('install_lib',), ('install_headers',), ('build',), ('build_scripts',), ('build_py',), ('build_ext',), ('build_clibs',), ('upload_sdist',), ('sdist',), ('register',), ('check',)], [('install',), ('install_distinfo',), ('install_data',), ('install_scripts',), ('install_lib',), ('install_headers',), ('test',), ('upload_bdist',), ('build',), ('build_scripts',), ('build_py',), ('build_ext',), ('build_clibs',), ('upload_sdist',), ('sdist',), ('register',), ('check',)], [('upload_sdist',), ('sdist',), ('install',), ('install_distinfo',), ('install_data',), ('upload_bdist',), ('register',), ('install_scripts',), ('install_lib',), ('install_headers',), ('test',), ('build',), ('build_scripts',), ('build_py',), ('build_ext',), ('build_clibs',), ('check',)], [('upload_sdist',), ('sdist',), ('upload_bdist',), ('register',), ('test',), ('install',), ('install_distinfo',), ('install_data',), ('install_scripts',), ('install_lib',), ('install_headers',), ('build',), ('build_scripts',), ('build_py',), ('build_ext',), ('build_clibs',), ('check',)], [('upload_sdist',), ('sdist',), ('upload_bdist',), ('register',), ('install',), ('install_distinfo',), ('install_data',), ('install_scripts',), ('install_lib',), ('install_headers',), ('test',), ('build',), ('build_scripts',), ('build_py',), ('build_ext',), ('build_clibs',), ('check',)], [('upload_sdist',), ('sdist',), ('install',), ('install_distinfo',), ('install_data',), ('install_scripts',), ('install_lib',), ('install_headers',), ('test',), ('upload_bdist',), ('build',), ('build_scripts',), ('build_py',), ('build_ext',), ('build_clibs',), ('register',), ('check',)])

tests/test_util.py:424: AssertionError
________________________________________________________________________________ UtilTestCase.test_cache_base _________________________________________________________________________________

self = <test_util.UtilTestCase testMethod=test_cache_base>

    def test_cache_base(self):
        actual = get_cache_base()
        if os.name == 'nt' and 'LOCALAPPDATA' in os.environ:
            expected = os.path.expandvars('$localappdata')
        else:
            expected = os.path.expanduser('~')
        expected = os.path.join(expected, '.distlib')
        self.assertEqual(expected, actual)
>       self.assertTrue(os.path.isdir(expected))
E       AssertionError: False is not true

tests/test_util.py:109: AssertionError
====================================================================================== warnings summary =======================================================================================
```

**To Reproduce**
Regular PyTest run.

**Environment**
 - OS, including version: FreeBSD 13.2
 - Version of this library: 0.3.7
- Python-3.9

**Comment by vsajip** [comment] 2023-07-18 08:46
Did you run with `PYTHONHASHSEED=0` defined in the environment? That's needed for the tests to pass. Note that there are no failures in the tests run via GitHub Actions.

**Comment by yurivict** [comment] 2023-07-18 09:24
2 tests still fail with ```PYTHONHASHSEED=0```:

```
========================================================================================== FAILURES ===========================================================================================
________________________________________________________________________________ UtilTestCase.test_cache_base _________________________________________________________________________________

self = <test_util.UtilTestCase testMethod=test_cache_base>

    def test_cache_base(self):
        actual = get_cache_base()
        if os.name == 'nt' and 'LOCALAPPDATA' in os.environ:
            expected = os.path.expandvars('$localappdata')
        else:
            expected = os.path.expanduser('~')
        expected = os.path.join(expected, '.distlib')
        self.assertEqual(expected, actual)
>       self.assertTrue(os.path.isdir(expected))
E       AssertionError: False is not true

tests/test_util.py:109: AssertionError
_______________________________________________________________________________ LocatorTestCase.test_dist_reqts _______________________________________________________________________________

self = <test_locators.LocatorTestCase testMethod=test_dist_reqts>

    @unittest.skipIf('SKIP_ONLINE' in os.environ, 'Skipping online test')
    @unittest.skipUnless(ssl, 'SSL required for this test.')
    def test_dist_reqts(self):
        r = 'config <=0.3.9'
        dist = default_locator.locate(r)
        self.assertIsNotNone(dist)
>       self.assertIsNone(dist.extras)
E       AssertionError: ['doc', 'test'] is not None

tests/test_locators.py:423: AssertionError
```

**Comment by vsajip** [comment] 2023-07-18 13:51
I can't reproduce these, and don't have access to a FreeBSD system. Can you enable logging and see if the logs give any more clues? For example, your home directory must be writeable for `test_cache_base()` to pass on POSIX.

You might need to set breakpoints in the tests to see what's going on.

**Comment by vsajip** [comment] 2023-07-18 15:24
I set up a FreeBSD VM for testing. Cannot reproduce with current repo contents:

![ss14](https://github.com/pypa/distlib/assets/130553/ba78b1ac-2215-43e9-8b70-c6009b8345c1)

Perhaps it's something specific to your installation.

**Comment by vsajip** [comment] 2023-07-18 15:39
I have limited time to investigate this - I suggest you turn on logging and see what that shows up, and perhaps use the debugger to see what's going on. What happens if you install `distlib` from PyPI rather than using the ports tree?

**Comment by vsajip** [comment] 2023-07-19 15:02
The problem could also be `pytest`-related. Please run the tests using `PYTHONHASHSEED=0 python3.9 tests/test_all.py` in the `...ports/devel/py-distlib/work-py39/distlib-0.3.7` directory. I didn't get any failures after multiple runs.

**Comment by vsajip** [comment] 2023-07-27 14:09
Closing, as no feedback received.

**Closed by vsajip** 2023-07-27 14:09 UTC
Labels: pending
